### ISSUE TITLE
Check Box

### ISSUE THREAD

**Issue by a2exfr** [juek/CustomSections#14]
Check box works only once.
Example: in shop_item impossible turn on the badge, after saving section with disabled badge.

**Comment by juek** [comment]
Thanks, [fixed](https://github.com/juek/CustomSections/commit/d8bad8bc6e23fc9d03602fe1e4ca127e2bac7db2)

**Comment by juek** [comment]
Currently checkbox uses '1' for checked/true and '0' for false/unchecked. 
What do you think? Should we go for 'true'/'false' 'on'/'off' instead?

**Comment by a2exfr** [comment]
1/0 is fine. I made it the same)) Just do not want to pull request because of doubts
