### ISSUE TITLE
CK editor field (image)

### ISSUE THREAD

**Issue by a2exfr** [juek/CustomSections#17]
When have image field and ckeditor field in one custom editor, when you want insert image in ckeditor field this image goes to editor image field)
Can we divide this callback? On first look I do not know where to dig...

**Comment by juek** [comment]
Hmm, this could become tricky....

**Comment by juek** [comment]
We need to destroy the gp_editor.FinderSelect once used... I'll try it

**Comment by a2exfr** [comment]
Once you wrote it, I just remember that I have done it before in otherr plug in!!! I have to look my folders)) I have two image select and editor there

**Comment by juek** [comment]
please try this:

```
  gp_editor.selectUsingFinder = function(callback_fn, input_selector){
    gp_editor.FinderSelect = function(fileUrl){ 
      if (fileUrl != "") {
        callback_fn(fileUrl, input_selector);
      }
      setTimeout(function(){
        gp_editor.FinderSelect = null;
      }, 150);
      return true;
    };
    var finderPopUp = window.open(gpFinderUrl, 'gpFinder', 'menubar=no,width=960,height=450');
    if( window.focus ){ 
      finderPopUp.focus(); 
    }
  }; // gp_editor.selectUsingFinder --end
```

my current codebase i not ready to commit.

**Comment by juek** [comment]
or better

  delete gp_editor.FinderSelect;

instead of 

  gp_editor.FinderSelect = null;

**Comment by juek** [comment]
but even ...

gp_editor.FinderSelect = false;

should work. Anything [that doesn't return a 'function'](https://github.com/Typesetter/Typesetter/blob/5966a684550a4565517ef27865c58b398b4ae42c/include/thirdparty/finder/config.js#L17) type will prevent the execution.

**Comment by a2exfr** [comment]
I was doing this like this in but in callback function 

gp_editor.FinderSelect="";

shame that I forgot about this

**Comment by juek** [comment]
LOL, yes, ="" will also work.

**Comment by juek** [comment]
> I was doing this like this in but in callback function

Since the callback_fn can be anything, doing it in FinderSelect with setTimeout will be easier and more safe.

**Comment by a2exfr** [comment]
mega lol that I made new issue about this, despite solve it in the past)

I agree about timeot, let me test it.

**Comment by juek** [comment]
> I made new issue about this, despite solve it in the past

Haha, yes, now I recall that we talked about this one earlier. Repetition improves memory :)

**Comment by a2exfr** [comment]
Just test it work good. Made [ pull request] (https://github.com/juek/CustomSections/pull/18)

**Comment by juek** [comment]
Thx. I'm currently working on module/component loader. Hope to commit soon.
