### ISSUE TITLE
Loading static content when not logged-in?

### ISSUE THREAD

**Issue by juek** [juek/CustomSections#2]
I just wonder if we should improve overall performance if we would save static section content to be loaded when logged off and only use the value processing pipeline when logged in?

**Comment by juek** [comment]
Hmm.... yes, just implemented :)

**Comment by a2exfr** [comment]
Value processing speed seems to be allright, but Im not shure about auto New sections how it affect perfomance

**Comment by juek** [comment]
> about auto New sections how it affect perfomance

I was also thinking about that. SectionTypes() gets called several times. I'd guess PHP (edit: or rather the OS itself) does some very efficient caching here because I can't see a remarkable impact yet. But it's not exactly beautiful this way :)

**Comment by juek** [comment]
I would say, let's leave it as it is for now and see what the future will bring ;)

**Comment by a2exfr** [comment]
> I would say, let's leave it as it is for now and see what the future will bring ;)

Ok, cause auto adding new sections  is quite comfortabl

**Comment by juek** [comment]
I already have an idea. 5 mins...

**Comment by juek** [comment]
Ok, it was 15 min. Just [commited](https://github.com/juek/CustomSections/commit/ebb9b8000fd9189eefd3c7fca801f4e1287f11d1) 

(of course it should read 'file')
