### ISSUE TITLE
Multi image control and section refresh

### ISSUE THREAD

**Issue by a2exfr** [juek/CustomSections#21]
Executing gp_editor.updateSection work no good with multi image control and take only one image(last) to refresh section.
I think tthis is no [go](https://github.com/juek/CustomSections/blob/master/universal_editor/editor.js#L88-L90) or I miss something.

Seems to me [this change](https://github.com/juek/CustomSections/pull/15/files) was working good with multi image.

edit: so cached stored content also wrong
edit2: may be take postC +   getValues function and formdata from my pull?
edit3: postC - cant work with formdata)

**Comment by a2exfr** [comment]
ok I got a  quick solution may be you corect it a little

```
	$.each(values_serialized, function(i, item) {
	if( item.name.slice(-2) =="[]"){
		var test=item.name.slice(0, -2);
		data[test]=[];
	}
		});
	
	$.each(values_serialized, function(i, item) {
 		if( item.name.slice(-2) =="[]"){
			var test=item.name.slice(0, -2);
			data[test].push(item.value);
		} else { 
			data[item.name] = item.value;
		}
		});
```


I dare to merge... also fix warniing empty needle when no dirprefix

**Comment by juek** [comment]
We could also numerically index every [], like ...

```
    var item_name = false;
    var new_idx = 0;
    $.each(values_serialized, function(i, item){
      if( item['name'] != item_name ){
        item_name = item['name'];
        new_idx = 0;
      }else{
        new_idx++;
      }
      item['name'] = item['name'].replace('[]', '[' + new_idx + ']');
      data[item['name']] = item['value'];
    });
```

But your way is smarter I guess.

**Comment by juek** [comment]
Um, and sorry for breaking your initially working function by using $gp.postC ;-)

**Comment by a2exfr** [comment]
not at all, postC is better cause in my function was ugly eval :)
