### ISSUE TITLE
Link field: via GPFinder is downloading PDF files instead of selecting it

### ISSUE THREAD

**Issue by thomasfrobieter** [juek/CustomSections#27]
Steps to reproduce it:

1. Insert the Shop Item
2. At button link, choose file via GPFinder (upload and try to select a pdf file)
3. The browser (firefox in my case) download the file instead of passing the file path to the link field

I thought it's up to GPFinder, but it's not.. linking an PDF file within CKEditor is working well.

**Comment by juek** [comment]
Thanks, [fixed](https://github.com/juek/CustomSections/commit/f3914e05364bf3eda91020ac4c938cedb77f8685)

**Comment by thomasfrobieter** [comment]
Great 👍 Thank's! Closed.
