### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mahotilo** [juek/CustomSections#31]
It will be good to have standard button to open mail form. 
We have button "Buy it" in Shop Item. But the only way to buy in Typesetter is to send a mail with item title, some customer info (name, address, phone), quantity and maybe some comments.
Such functionality makes from TS very good Simple Shop CMS. IMHO

**Comment by juek** [comment]
Certainly. The shop_item type is–like all included section types–only a demo. Custom form submission and -processing, besides lots of other things, is possible via section.php. All Typesetter classes and methods that can be used in section context are available here.

**Comment by mahotilo** [comment]
Thanks, I'll try to take a closer look
