### ISSUE TITLE
Add more JS callback functions

### ISSUE THREAD

**Issue by thomasfrobieter** [juek/CustomSections#32]
Hey, 

can we please add some more callback funktions inside the universal_editor/editor.js? Currently we just have "CustomSection:updated" available.

Specificly i added:
```
  gp_editor.getFormElements = function(){
    var form_elements = gp_editor.ui.controls
      //.find("input:not(.editor-ctl-no-submit, [type='checkbox'], [type='radio'], [data-applyto]), select:not([data-applyto]), textarea");
      .find("input:not(.editor-ctl-no-submit, [type='checkbox'], [type='radio']), select, textarea")
      .trigger("CustomSection:formElementsLoaded"); // NEW LINE
    return form_elements;
  };
```

**Comment by juek** [comment]
[Sure thing](https://github.com/juek/CustomSections/commit/2f19cb80749f47cf68eebf80c502391670c16546).

When triggered frome here, this event will fire quite frequently:  
Once on every form element, everytime checkDirty, resetDirty, SaveData or updateSection are called. 

Are you sure you really need them this way?
We also have the ["editor_area:loaded" event](https://github.com/Typesetter/Typesetter/blob/2f3ab92c341ad65b0cda6522e2f3d21f6029fa99/include/js/inline_edit/inline_editing.js#L239)

**Comment by thomasfrobieter** [comment]
Yes editor_area:loaded is exactly what i need, thank you! I just saw the "CustomSection:updated" callback. Can we add a list of callbacks to the description / readme?

**Comment by juek** [comment]
AFAIK, we currently only trigger the "CustomSection:updated" custom event in $gp.response.updateContent()
Another way to execute JS is to write a 

```
CustomSections.onUpdate = function(){ 
  $(this).doSomething(); // this is the currently edited section
};
```
which will be called in the same response.

[editor_area:loaded](https://github.com/Typesetter/Typesetter/blob/2f3ab92c341ad65b0cda6522e2f3d21f6029fa99/include/js/inline_edit/inline_editing.js#L239) will be triggered by Typesetter/inline_editing.js.

Some other useful events: 
[section_sorting:loaded](https://github.com/Typesetter/Typesetter/blob/092e3c946beaddc4235279bb953f84edf4fd0fae/include/js/inline_edit/manage_sections.js#L130)
[section_options:loaded](https://github.com/Typesetter/Typesetter/blob/092e3c946beaddc4235279bb953f84edf4fd0fae/include/js/inline_edit/manage_sections.js#L653)
[SectionAdded](https://github.com/Typesetter/Typesetter/blob/092e3c946beaddc4235279bb953f84edf4fd0fae/include/js/inline_edit/manage_sections.js#L425)
[SectionSorted](https://github.com/Typesetter/Typesetter/blob/092e3c946beaddc4235279bb953f84edf4fd0fae/include/js/inline_edit/manage_sections.js#L278)
[PreviewAdded](https://github.com/Typesetter/Typesetter/blob/092e3c946beaddc4235279bb953f84edf4fd0fae/include/js/inline_edit/manage_sections.js#L383)
[PreviewRemoved](https://github.com/Typesetter/Typesetter/blob/092e3c946beaddc4235279bb953f84edf4fd0fae/include/js/inline_edit/manage_sections.js#L400)
[SectionRemoved](https://github.com/Typesetter/Typesetter/blob/092e3c946beaddc4235279bb953f84edf4fd0fae/include/js/inline_edit/manage_sections.js#L442)

**Comment by thomasfrobieter** [comment]
Yeah i think you have shown me this callbacks a while a go, i already saved it (http://blog.frobieter.de/content/typesetter-documentation) - except editor_area:loaded :)

Thank's again!

**Comment by thomasfrobieter** [comment]
But the CustomSection:formElementsLoaded is still very helpfull, as it fires also if a bunch control popup is loaded.

**Comment by thomasfrobieter** [comment]
CustomSection:formElementsLoaded  fires way to often on the position i choosed -_- I think we can remove it.

But i added some more helpfull callbacks for bunch controls, i will push the changes.

**Comment by juek** [comment]
regarding SectionCopied:

>i already saved it (http://blog.frobieter.de/content/typesetter-documentation) -> SectionCopied (Unclear - looks like only SectionAdded fired if a section is copied)

True. CopySection() in fact creates a clone (non-deep) via JS, which is - from the CMS point-of-view - nothing but an additional section, once saved. Source and copy aren't linked in any way (no inheritance or common properties). Therefore the SectionAdded event gets fired. 

Hmm, maybe we should also fire a "SectionCopied" event, e.g. for cases where we need to generate new unique ids. Actually, IMO such ids should be (re)generated client-side when SectionAdded fires.
