### ISSUE TITLE
glyphicons

### ISSUE THREAD

**Issue by mahotilo** [juek/CustomSections#36]
I make a tests with shop_item type.
I want to mate it with jquery.mycart and I have a problem with `class="glyphicon glyphicon-shopping-cart"`.
I try to add `$components = 'bootstrap-all'` and `$css_files = array('include/thirdparty/Bootstrap3/css/bootstrap.min.css',);` but still see no glyphicon.
Can you point a right way to me to force it work?

**Comment by juek** [comment]
If you're in a Bootstrap or Bootwatch based theme, you don't need to include bootstrap again.

Th easiest way to make it work that I found was to …

* Create a 'fonts' directory in your theme directory. E.g. /themes/Bootswatch_Scss/fonts
* Create a 'bootstrap' directory in the fonts' dir /themes/Bootswatch_Scss/fonts/bootstrap
* Copy the 5 font files from /include/thirdparty/Bootstrap3/fonts/ to this directory.

For whatever exact reason, the css points to this location.

**Comment by mahotilo** [comment]
Thx!

> For whatever exact reason, the css points to this location.

Yes, I see it in console. I thinked that there is a way to use font from
\include\thirdparty\Bootstrap3\fonts

As for now I decide to change `glyphicon glyphicon-shopping-cart` on `fa fa-shopping-cart` because I need to change  jquery.mycart anyway.

**Comment by juek** [comment]
Fine. FontAwesome is simpler to activate.

I have no clue how the $bootstrap-sass-asset-helper thing works. Glyphicons loading is somehow bound to that function, which is disabled in Bootswatch themes by deafult.

**Comment by mahotilo** [comment]
Thx
Now I try to activate dotdotdot : )
I understand more and more what a great thing is CustomSections
