### ISSUE TITLE
i18n array

### ISSUE THREAD

**Issue by mahotilo** [juek/CustomSections#38]
We have 
```
self::$i18n['section']['lang'];
self::$i18n['editor']['lang'];
```
Does it corresponds to
```
$section_lang = array();
$editor_lang = array();
```
in `en.php`?
 
Looks like we always use only strings from
`$section_lang = array();`

**Comment by mahotilo** [comment]
Another i18n question.

I want to do something like this in `section.php`
```
$section_lang = self::$i18n['section']['lang'];
...
$javascript = 'var $MYCART_LANG = '.json_encode($section_lang).';';
```
to pass strings into JS plugin.
But I get an empty array.

If I load `en.php` directly in `section.php` all works fine

If I correctly understand, we need to initialize `$i18n` a bit earlier?

P.S.
And sorry, I give you an enigma but I will be off-line for a couple of days:)

**Comment by juek** [comment]
> Looks like we always use only strings from $section_lang = array();

They are only different if you are using Multi-Language Manager. If so, the editor will always use Typesetter's config language, while the content section will adopt the language of the current page.

**Comment by juek** [comment]
> If I correctly understand, we need to initialize $i18n a bit earlier?

Absolutely correct. And [fixed](https://github.com/juek/CustomSections/commit/fd5a3673be0740d17f3cef8a34d066d8e9edc824)

**Comment by juek** [comment]
> Does it corresponds to
> $section_lang = array();
> $editor_lang = array();

No, there is only $section_lang
The differentiation happens only when Multi-Language Manager's page language deviates from Typesetter's admin ui language.

edit/ Maybe needs explanation:
The $section_lang array in /i18n/*.php may contain terms/translations for both editor components and page content output.  With Multi-Language Manager running, pages may have different languages assigned. 
This way, for example, we can still have the admin UI running in english but the generated content will obey the page language, e.g. french, ukraininan, you name it --> So you will see the editor in english but the rendered page in french.

**Comment by mahotilo** [comment]
Thanks, all works. 
And I agree with yours vision of i18n. Word "section" simply misguided me.
