### ISSUE TITLE
Universal Editor -> admin page?

### ISSUE THREAD

**Issue by juek** [juek/CustomSections#4]
Sth. for the future, maybe. 

With the universal editor, we could even make an Admin page to define new sections, which could be stored in $addonPathData/_types (or even in JSON format in /data/_uploaded/CusomSections/_types, hence they could be managed via finder. LOL)

We could then assign editor controls to values using some graphical UI, add uploaded images/media as default cotent, etc. 

For conditional rendering we'd need an idea, though.

Well, maybe some time.

**Comment by a2exfr** [comment]
Sth.for future:
Admin page with
Tool to regenerate stored section content on selected page of selected section type.
Recent situation : When suddenly need change something in section and allready have 40 section on page, with some info...
Of cause we have "always_process_values", but still...

**Comment by juek** [comment]
> Tool to regenerate stored section content on selected page

I agree that we need this in case there are lots of existing sections and we need to change/extend the type. 
But that's merely a developer feature, so I'd go for an additional cmd such as 'recreate_custom_sections' to be executed on a page. Finding all pages/extra areas with certain types might be overkill. 

What do you think?

**Comment by a2exfr** [comment]
> But that's merely a developer feature, so I'd go for an additional cmd such as 'recreate_custom_sections' to be executed on a page. 

Not bad!! 👍 that's better idea

Actually I want this plugin to be productive dev tool, I think approach to make it usable for average users will kill flexibility.

**Comment by juek** [comment]
> I think approach to make it usable for average users will kill flexibility

Actually there is way too much insecure, low-level stuff in here to make it accessible via an Admin page to users. A single typo can cause a fatal error, rendering the whole CMS dead. It is definitely developer level.

Therefore ... agreed ;-)

**Comment by juek** [comment]
Abandoned (at least for the near future)
