### ISSUE TITLE
Multilanguage for Recaptcha

### ISSUE THREAD

**Issue by mahotilo** [juek/CustomSections#44]
Hi, Juergen.

I need to setup recaptcha language when using Multilanguage plugin. 
I see no global for current page language. I suppose it  should be $page_lang.
As for now I copy code from CustomSections.php circa line 661.

Can we have current page language global?

P.S. This request's priority is very low until... :)

**Comment by juek** [comment]
> Can we have current page language global?

Not as far as i know. Admittedly, I haven't checked the latest Multi-Language Manager changes, so the setLanguage function might be simpler since MLM 1.2.2. 

I believe MLM itself should set $page->language - which would make a lot of things way easier.

**Comment by juek** [comment]
implemented with [this commit](https://github.com/juek/Multi-Language/commit/acb5ceeb2bfd7d7bbcedf4c99d10c8340d3eeef1#diff-c1ff292c838f772813892683e3edd75dR251)

... some 20 months ago.
Years go by :)
